module.exports = {
    "ProjectName" : "",
    "RootNamespace" : "",
    "TargetFrameworkVersion" : "",
    "OutputFile" : "",
    "ArtifactId" : "",
    "ArtifactExtension" : "",
    "Remote" : "",
    "UserName" : "",
    "Owner" : "",
    "UserEmail" : "",
    "WebServer" : "",
    "ProjectGuid" : "",
    "ComGuid" : "",
    "SolutionGuid" : "",
    "AssemblyName" : "",
    "AssemblyVersion" : "",
    "AssemblyVersionQualifier" : ""
}
