#!/bin/sh

echo usage Examples
echo iwant c# MyExecutable Com.Company.MySuite v4.5 WinExe 1.0.0.0 -SNAPSHOT
echo iwant c# MyLibrary Com.Company.MySuite v4.5 Library 1.0.0.0 -SNAPSHOT

[[ -z "$1" ]] && TEMPLATE="c#" || TEMPLATE="$1"
[[ -z "$2" ]] && NAME="MyApp" || NAME="$2"
[[ -z "$3" ]] && PACKAGE="MyPackage" || PACKAGE="$3"
[[ -z "$4" ]] && VERSION="v4.5" || VERSION="$4"
[[ -z "$5" ]] && TYPE="WinExe" || TYPE="$5"
[[ -z "$6" ]] && ASSEMBLYVERSION="1.0.0.0" || ASSEMBLYVERSION="$6"
[[ -z "$7" ]] && ASSEMBLYVERSIONQUALIFIER="-SNAPSHOT" || ASSEMBLYVERSIONQUALIFIER="$7"

PROJECTGUID=`uuidgen`
COMGUID=`uuidgen`

TEMPLATEDIR=templates/${TEMPLATE}
FOLDER=${NAME}
echo using template ${TEMPLATE}
echo using folder ${FOLDER}
echo using name ${NAME}
echo using package ${PACKAGE}
echo using version ${VERSION}
echo using type ${TYPE}
echo using project guid ${PROJECTGUID}
echo using COM guid ${COMGUID}
echo using assembly version ${ASSEMBLYVERSION}
echo using assembly version qualifier ${ASSEMBLYVERSIONQUALIFIER}

if [ ! -d "$TEMPLATEDIR" ]; then
  echo template ${TEMPLATE} does not exist.
  exit 1
fi

if [ -d "$FOLDER" ]; then
  echo destination ${FOLDER} already exists.
  exit 1
fi

cp -R ${TEMPLATEDIR} ${FOLDER}
cd ${FOLDER}

SEDXX='sed 
 -e s/\${AssemblyName}/'${NAME}'/ 
 -e s/\${RootNamespace}/'${PACKAGE}'/ 
 -e s/\${TargetFrameworkVersion}/'${VERSION}'/ 
 -e s/\${OutputType}/'${TYPE}'/ 
 -e s/\${ProjectGuid}/'${PROJECTGUID}'/ 
 -e s/\${ComGuid}/'${COMGUID}'/ 
 -e s/\${AssemblyVersion}/'${ASSEMBLYVERSION}'/ 
 -e s/\${AssemblyVersionQualifier}/'${ASSEMBLYVERSIONQUALIFIER}'/'

echo using substitution command ${SEDXX}

${SEDXX} App.csproj > ${PACKAGE}.${NAME}.csproj
${SEDXX} App.cs > ${NAME}.cs
${SEDXX} Properties/AssemblyInfo.cstemplate > Properties/AssemblyInfo.cs
${SEDXX} pom.xmltemplate > pom.xml

rm App.csproj
rm App.cs
rm Properties/AssemblyInfo.cstemplate
rm pom.xmltemplate
